$filePath = "i:\wp-pdf-builder-pro-V2\plugin\templates\admin\settings-parts\settings-licence.php"
$content = Get-Content $filePath -Raw

# Remplacer toutes les classes
$replacements = @{
    'class="status-card-header"' = 'class="license-status-card-header"'
    'class="status-icon' = 'class="license-status-icon'
    'class="status-info' = 'class="license-status-info'
    'class="status-subtitle"' = 'class="license-status-subtitle"'
    'class="status-details"' = 'class="license-status-details"'
    'class="status-metrics"' = 'class="license-status-metrics"'
    'class="metric-item"' = 'class="license-metric-item"'
    'class="metric-label"' = 'class="license-metric-label"'
    'class="metric-value"' = 'class="license-metric-value"'
    'class="test-mode-banner"' = 'class="license-test-mode-banner"'
    'class="alert-icon"' = 'class="license-alert-icon"'
    'class="alert-content"' = 'class="license-alert-content"'
    'class="alert-date"' = 'class="license-alert-date"'
    'class="alert-actions"' = 'class="license-alert-actions"'
    'class="btn-small' = 'class="license-btn-small'
    'class="action-card' = 'class="license-action-card'
    'class="action-icon"' = 'class="license-action-icon"'
    'class="feature-item' = 'class="license-feature-item'
    'class="feature-icon"' = 'class="license-feature-icon"'
    'class="feature-content' = 'class="license-feature-content'
    'class="upgrade-prompt"' = 'class="license-upgrade-prompt"'
    'class="details-grid"' = 'class="license-details-grid"'
    'class="detail-card' = 'class="license-detail-card'
    'class="copy-btn' = 'class="license-copy-btn'
    '.status-card-header {' = '.license-status-card-header {'
    '.status-icon {' = '.license-status-icon {'
    '.status-info h3 {' = '.license-status-info h3 {'
    '.status-subtitle {' = '.license-status-subtitle {'
    '.status-details {' = '.license-status-details {'
    '.status-metrics {' = '.license-status-metrics {'
    '.metric-item {' = '.license-metric-item {'
    '.metric-label {' = '.license-metric-label {'
    '.metric-value {' = '.license-metric-value {'
    '.test-mode-banner {' = '.license-test-mode-banner {'
    '.alert-icon {' = '.license-alert-icon {'
    '.alert-content h4 {' = '.license-alert-content h4 {'
    '.alert-date {' = '.license-alert-date {'
    '.alert-actions {' = '.license-alert-actions {'
    '.btn-small {' = '.license-btn-small {'
    '.btn-small.primary {' = '.license-btn-small.primary {'
    '.btn-small:hover {' = '.license-btn-small:hover {'
    '.action-card {' = '.license-action-card {'
    '.action-card.secondary {' = '.license-action-card.secondary {'
    '.action-card-header h3 {' = '.license-action-card-header h3 {'
    '.action-card-header p {' = '.license-action-card-header p {'
    '.action-icon {' = '.license-action-icon {'
    '.input-with-button' = '.license-input-with-button'
    '.input-help' = '.license-input-help'
    '.link-primary {' = '.license-link-primary {'
    '.link-primary:hover' = '.license-link-primary:hover'
    '.dev-mode-status {' = '.license-dev-mode-status {'
    '.status-active,' = '.license-status-active,'
    '.status-inactive {' = '.license-status-inactive {'
    '.status-dot {' = '.license-status-dot {'
    '.status-dot.active {' = '.license-status-dot.active {'
    '.status-dot.inactive {' = '.license-status-dot.inactive {'
    '.expiry-info' = '.license-expiry-info'
    '.premium-features-section {' = '.license-premium-features-section {'
    '.section-title {' = '.license-section-title {'
    '.section-icon {' = '.license-section-icon {'
    '.details-grid {' = '.license-details-grid {'
    '.detail-card {' = '.license-detail-card {'
    '.detail-card h4 {' = '.license-detail-card h4 {'
    '.detail-value {' = '.license-detail-value {'
    '.copy-btn {' = '.license-copy-btn {'
    '.copy-btn:hover {' = '.license-copy-btn:hover {'
    '.test-badge {' = '.license-test-badge {'
    '.status-badge {' = '.license-status-badge {'
    '.status-badge.active {' = '.license-status-badge.active {'
    '.status-badge.free {' = '.license-status-badge.free {'
    '.status-badge.test {' = '.license-status-badge.test {'
    '.features-grid {' = '.license-features-grid {'
    '.feature-item {' = '.license-feature-item {'
    '.feature-item.unlocked {' = '.license-feature-item.unlocked {'
    '.feature-item.locked {' = '.license-feature-item.locked {'
    '.feature-icon {' = '.license-feature-icon {'
    '.feature-content h4 {' = '.license-feature-content h4 {'
    '.feature-content p {' = '.license-feature-content p {'
    '.upgrade-prompt {' = '.license-upgrade-prompt {'
    '.upgrade-prompt h4 {' = '.license-upgrade-prompt h4 {'
    '.upgrade-prompt p {' = '.license-upgrade-prompt p {'
    '.premium-support:hover' = '.license-premium-support:hover'
    '.feature-item:hover' = '.license-feature-item:hover'
    '.premium-cta:hover' = '.license-premium-cta:hover'
    '.premium-cta:hover div' = '.license-premium-cta:hover div'
    '.premium-promo:hover' = '.license-premium-promo:hover'
}

foreach ($old in $replacements.Keys) {
    $new = $replacements[$old]
    $content = $content -replace [regex]::Escape($old), $new
}

Set-Content $filePath $content -Encoding UTF8
Write-Host "✅ Classes préfixées avec succès"
