$content = Get-Content "resources/js/components/PDFEditor.jsx"
$content[1923] = "                  // Pour l''adresse, afficher toujours l''icône sur la première ligne"
$content[1924] = "                  if (field === ''address'' && lineIndex === 0) {"
$content[1925] = "                    const label = field.charAt(0).toUpperCase() + field.slice(1).replace(''_'', '' '');"
$content[1926] = "                    displayText = `""${icon} ${line}""`;"
$content[1927] = "                  }"
$content[1928] = "                  // Ajouter l''étiquette seulement à la première ligne si demandée (pour les autres champs)"
$content[1929] = "                  else if (showLabels && lineIndex === 0) {"
$content | Set-Content "resources/js/components/PDFEditor.jsx"
